crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("products/", include("products.urls")),
    path("ads/", include("advertisements.urls")),
    path("leads/", include("leads.urls")),
    path("contracts/", include("contracts.urls")),
    path("customers/", include("customers.urls")),
    path("", include("crmsystem.urls")),
]

crm/crmsystem/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import (
    IndexTemplateView,
    LogoutView,
)


app_name = "crmsystem"  # pylint: disable=invalid-name

urlpatterns = [
    path("", IndexTemplateView.as_view(), name="index"),
    path(
        "login/",
        LoginView.as_view(
            template_name="registration/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
]

crm/contracts/models.py
from datetime import date

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models

from products.models import Product


class Contract(models.Model):
    """
    Модель Контракта
    """

    def upload_document(self, filename):
        """
        Определение пути для файла документа по id Контракта
        """
        extension = filename.split(".")[-1]
        pk = self.pk - 1 if self.pk is not None else self.pk
        if not pk:
            obj = Contract.objects.order_by("-id").first()  # pylint: disable=no-member
            pk = obj.id if obj is not None else 0
        return f"documents/{pk + 1}.{extension}"

    name = models.CharField(max_length=250)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    document = models.FileField(upload_to=upload_document)
    start_date = models.DateField()
    end_date = models.DateField()
    cost = models.DecimalField(
        decimal_places=2, max_digits=12, validators=[MinValueValidator(0)]
    )

    def clean(self):
        errors = {}
        if (self.end_date - self.start_date).total_seconds() < 0:
            errors["start_date"] = "start date must be less than or equal to end date"
            errors["end_date"] = "end date must be greate than or equal to start date"
        if (date.today() - self.start_date).total_seconds() < 0:
            errors["start_date"] = (
                "start date must be greater than or equeal to today's day"
            )
        if errors:
            raise ValidationError(errors)

    def __str__(self):
        return self.name + " - " + self.product.name

crm/customers/models.py
from django.db import models

from contracts.models import Contract
from leads.models import Lead


class Customer(models.Model):
    """
    Модель Клиента
    """

    lead = models.OneToOneField(
        Lead, on_delete=models.CASCADE, limit_choices_to={"is_customer": False}
    )
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        super().save(force_insert, force_update, using, update_fields)
        self.lead.is_customer = True
        self.lead.save()  # pylint: disable=no-member

    def __str__(self):
        return (
            self.lead.last_name  # pylint: disable=no-member
            + " "
            + self.lead.first_name  # pylint: disable=no-member
        )

crm/leads/models.py
from django.db import models


class Lead(models.Model):
    """
    Модель Потенциального Клиента
    """

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=14)
    email = models.EmailField()
    ad = models.ForeignKey("advertisements.Advertisement", on_delete=models.CASCADE)

    is_customer = models.BooleanField(default=False)

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        super().save(force_insert, force_update, using, update_fields)
        self.ad.save()  # pylint: disable=no-member

    def __str__(self):
        return self.last_name + " " + self.first_name

crm/products/models.py
from django.core.validators import MinValueValidator
from django.db import models


class Product(models.Model):
    """
    Модель Услуги
    """

    name = models.CharField(max_length=250)
    description = models.TextField()
    cost = models.DecimalField(
        max_digits=12, decimal_places=2, validators=[MinValueValidator(0)]
    )

    def __str__(self):
        return str(self.name)

crm/crmsystem/views.py
from django.contrib.auth import logout
from django.http import HttpRequest
from django.shortcuts import redirect
from django.views import View
from django.views.generic import (
    TemplateView,
)

from advertisements.models import Advertisement
from customers.models import Customer
from leads.models import Lead
from products.models import Product


class IndexTemplateView(TemplateView):
    """
    Представление главной страницы приложения
    """

    template_name = "users/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["products_count"] = Product.objects.count()  # pylint: disable=no-member
        context["advertisements_count"] = (
            Advertisement.objects.count()  # pylint: disable=no-member
        )
        context["leads_count"] = Lead.objects.filter(  # pylint: disable=no-member
            is_customer=False
        ).count()
        context["customers_count"] = (
            Customer.objects.count()  # pylint: disable=no-member
        )
        return context


class LogoutView(View):
    """
    Представление выхода пользователя из аккаунта
    """

    def get(self, request: HttpRequest):
        """
        Метод выхода из аккаунта пользователя
        """
        logout(request)
        return redirect("crmsystem:login")

crm/crmsystem/templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>CRM</title>
</head>
<body>

<div class="main-container d-flex">
    <div class="sidebar" id="side_nav">
        <div class="header-box px-3 pt-4 pb-4">
            <h1 class="fs-4 nav-logo">
                <span class="text-black text-uppercase font-weight-bold">
                    <a class="link-dark text-decoration-none" href="/">CRM BACKOFFICE</a>
                </span>
            </h1>
        </div>
        <ul class="list-unstyled px-2">
            {% if perms.products.view_product %}
            <li><a href="/products/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-microchip"></i></span><span class="ml-1"> Услуги</span>
            </a></li>
            {% endif %}
            {% if perms.advertisements.view_advertisement %}
            <li><a href="/ads/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-ad"></i></span><span class="ml-1"> Рекламные компании</span>
            </a></li>
            {% endif %}
            {% if perms.leads.view_lead %}
            <li><a href="/leads/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-clock"></i></span><span class="px-1"> Лиды</span>
            </a></li>
            {% endif %}
            {% if perms.contracts.view_contract %}
            <li><a href="/contracts/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-file-alt"></i></span><span class="px-1"> Контракты</span>
            </a></li>
            {% endif %}
            {% if perms.customers.view_customer %}
            <li><a href="/customers/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-check"></i></span><span class="px-1"> Активные клиенты</span>
            </a></li>
            {% endif %}
            <li>
                <hr>
            </li>
            <li><a href="/logout" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-sign-out-alt"></i></span><span class="px-1"> Выход</span>
            </a></li>
        </ul>
    </div>
    <div class="content px-3 pt-4">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>